lib/home73k_web/router.ex
defmodule Home73kWeb.Router do
  use Home73kWeb, :router
  alias Home73kWeb.CSPHeader

  pipeline :browser do
    plug :accepts, ~w(html xml)
    plug :fetch_session
    plug :fetch_live_flash
    plug :put_root_layout, {Home73kWeb.LayoutView, :root}
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug CSPHeader
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", Home73kWeb do
    pipe_through :browser

    # Pages
    get "/", HomeController, :index
    get "/about", HomeController, :about
    get "/resume", HomeController, :resume
    get "/folio", HomeController, :folio

    # Blog
    live "/blog", BlogLive, :index
    live "/blog/page/:page", BlogLive, :page
    live "/blog/tag/:tag", BlogLive, :tag
    live "/blog/:id", BlogLive, :show

    # Feeds
    get "/feed", FeedController, :rss

    # Error fun/testing
    get "/err", ErrController, :err
    get "/err/:code", ErrController, :err
  end

  # Other scopes may use custom stacks.
  # scope "/api", Home73kWeb do
  #   pipe_through :api
  # end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser
      live_dashboard "/dashboard", metrics: Home73kWeb.Telemetry
    end
  end
end

lib/home73k_web/controllers/feed_controller.ex
defmodule Home73kWeb.FeedController do
  use Home73kWeb, :controller
  plug :put_layout, false
  plug :put_root_layout, false

  alias Home73k.Blog

  def rss(conn, _params) do
    posts = Blog.list_posts()
    last_build_date = posts |> List.first() |> Map.get(:date)

    conn
    |> put_resp_content_type("application/rss+xml")
    |> render("rss.xml", posts: posts, last_build_date: last_build_date)
  end
end

lib/home73k_web/views/feed_view.ex
defmodule Home73kWeb.FeedView do
  use Home73kWeb, :view

  import Home73k, only: [app_time_zone: 0]

  def to_rfc822(naive_dt) do
    naive_dt
    |> DateTime.from_naive!(app_time_zone())
    |> Calendar.strftime("%a, %d %b %Y %H:%M:%S %Z")
  end
end

lib/home73k_web/templates/feed/rss.xml.eex
<?xml version="1.0" encoding="utf-8"?>
<rss version="2.0" xmlns:atom="http://www.w3.org/2005/Atom">
  <channel>
    <title>73k Blog - Adam Piontek</title>
    <link><%= Routes.blog_url(@conn, :index) %></link>
    <atom:link href="<%= Routes.feed_url(@conn, :rss) %>" rel="self" type="application/rss+xml" />
    <description>Blog by Adam Piontek. Desktop Systems Engineer. Human. Casual anthropologist, cautious DIYer, cuckoo leftist, cat papa.</description>
    <language>en</language>
    <copyright>Copyright <%= DateTime.utc_now.year %> Adam Piontek</copyright>
    <lastBuildDate><%= @last_build_date |> to_rfc822 %></lastBuildDate>
    <category>Personal/Political/Society/Technology/IT/Internet/Web development</category>
    <ttl>60</ttl><%= for post <- @posts do %>
      <item>
        <title><%= post.title |> String.replace(" & ", " &amp; ") %></title>
        <link><%= Routes.blog_url(@conn, :show, post) %></link>
        <guid><%= Routes.blog_url(@conn, :show, post) %></guid>
        <description><![CDATA[ <%= post.lede |> String.replace("href=\"/", "href=\"#{Routes.home_url(@conn, :index)}") %> ]]></description>
        <category><%= post.tags |> List.first() %></category>
        <pubDate><%= post.date |> to_rfc822 %></pubDate>
        <source url="<%= Routes.feed_url(@conn, :rss) %>">73k Blog - Adam Piontek</source>
      </item><% end %>
  </channel>
</rss>